param (
    [Parameter()]
    [System.Collections.Hashtable]
    $Options,
    [Parameter()]
    [System.Collections.Hashtable]
    $Overrides
)

if ($Overrides.SkinDirectory) { $dir = $Overrides.SkinDirectory.Trim() } else { $dir = "Settings" }

$RmAPI.Log($Overrides.SkinDirectory)

return @"
[Metadata]
Name=settings by: Settings
Author=Sceleri
Information=This settings skin was generated by Settings! https://github.com/sceleri/settings
Version=1.4
License=CC BY-NC-SA 4.0

[Rainmeter]
Update=-1
;This updates measures like the scroll measure once
OnRefreshAction=[!Update][!Redraw]
AccurateText=1
@IncludeSkinVariables=$($Options.SettingsFile)
@IncludesOnChangeAction=#ROOTCONFIGPATH#$($dir)\Includes\s_OnChangeAction.inc
@IncludeInternalVariables=#ROOTCONFIGPATH#$($dir)\Includes\Variables.inc
@IncludeTheme=$($Options.ThemeFile)
SkinHeight=[#s_PanelH]
SkinWidth=([#s_LeftPanelW] + [#s_RightPanelW])

[FrostedGlass]
Measure=Plugin
Plugin=FrostedGlass
Type=[#s_FrostedGlassMode]
Border=[#s_FrostedGlassBorders]

[IncludeMeterStyles]
@IncludeMeterStyles=#ROOTCONFIGPATH#$($dir)\Includes\MeterStyles.inc

[IncludeBackground]
@IncludeBackground=#ROOTCONFIGPATH#$($dir)\Includes\Background.inc

[IncludeCategoryList]
@IncludeCategoryList=#ROOTCONFIGPATH#$($dir)\Categories\CategoryList.inc

[IncludeCurrentCategory]
@IncludeCategory=#ROOTCONFIGPATH#$($dir)\Categories\[#s_CurrentCategory].inc

[IncludeTitleBar]
@IncludeBackground=#ROOTCONFIGPATH#$($dir)\Includes\TitleBar.inc


"@

