param (
    [Parameter()]
    [System.Collections.Hashtable]
    $Options
)

$ini = @"
[Metadata]
Name=settings by: Settings
Author=Sceleri
Information=This settings skin was generated by Settings! https://github.com/sceleri/settings
Version=1.4
License=CC BY-NC-SA 4.0

[Rainmeter]
Update=-1
@IncludeSkinVariables=$($Options.SettingsFile)
@IncludesOnChangeAction=#ROOTCONFIGPATH#settings\includes\s_OnChangeAction.inc
@IncludeInternalVariables=#ROOTCONFIGPATH#settings\includes\Variables.inc
SkinHeight=[#s_PanelH]
;SkinWidth=([#s_LeftPanelW] + [#s_RightPanelW])

[Theme]
@IncludeTheme=$($Options.ThemeFile)

[FrostedGlass]
Measure=Plugin
Plugin=FrostedGlass
Type=[#s_FrostedGlassMode]
Border=[#s_FrostedGlassBorders]

[IncludeBackground]
@IncludeBackground=#ROOTCONFIGPATH#settings\includes\Background.inc

[IncludeMeterStyles]
@IncludeMeterStyles=#ROOTCONFIGPATH#settings\includes\MeterStyles.inc

[IncludeListItems]
@IncludeListItems=#ROOTCONFIGPATH#settings\includes\ListItems.inc

[IncludeCategoryList]
@IncludeCategoryList=#ROOTCONFIGPATH#settings\categories\CategoryList.inc

[IncludeCurrentCategory]
@IncludeCategory=#ROOTCONFIGPATH#settings\categories\[#s_CurrentCategory].inc


"@

return $ini
