[Rainmeter]
Update=-1
@IncludeSkinVariables={SettingsFile}
@IncludeVariables=#ROOTCONFIGPATH#settings\includes\Variables.inc

[IncludeBackground]
@IncludeBackground=#ROOTCONFIGPATH#settings\includes\Background.inc

[IncludeMeterStyles]
@IncludeBackground=#ROOTCONFIGPATH#settings\includes\MeterStyles.inc

[IncludeCategoryList]
@IncludeCategoryList=#ROOTCONFIGPATH#settings\categories\CategoryList.inc

[IncludeCurrentCategory]
@IncludeCategory=#ROOTCONFIGPATH#settings\categories\[#s_CurrentCategory].inc

