param (
    [Parameter()]
    [System.Collections.Hashtable]
    $Overrides
)

return @"
[TitleBar]
Meter=Shape
Shape=Rectangle 0,0,(#s_RightPanelW# + #s_LeftPanelW#),(#s_TopHeight#),(#s_BackgroundRounding#) | Extend BackgroundModifiers
Shape2=Rectangle 0,(#s_TopHeight# - (#s_BackgroundRounding#)),(#s_RightPanelW# + #s_LeftPanelW#),(([#s_HideTopCorrector] = 0) ? #s_BackgroundRounding# : 0) | Extend BackgroundModifiers
BackgroundModifiers=Fill Color #s_TopBarColor# | StrokeWidth 0

[Close]
Meter=Shape
Shape=Ellipse 0,0,([#s_CBS] / 2) | Fill Color [#s_CloseButtonColor] | StrokeWidth [#s_CloseButtonStrokeWidth] | Stroke Color [#s_CloseButtonStrokeColor]
Shape2=Line (Cos(0.7854)  * [#s_CBS] / 2 * [#s_CS]), (Sin(0.7854)  * [#s_CBS] / 2 * [#s_CS]), (Cos(0.7854)  * [#s_CBS] / -2 * [#s_CS]), (Sin(0.7854)  * [#s_CBS] / -2 * [#s_CS]) | StrokeWidth [#s_CloseCrossThick] | Stroke Color [#s_CloseCrossColor]
Shape3=Line (Cos(-0.7854) * [#s_CBS] / 2 * [#s_CS]), (Sin(-0.7854) * [#s_CBS] / 2 * [#s_CS]), (Cos(-0.7854) * [#s_CBS] / -2 * [#s_CS]), (Sin(-0.7854) * [#s_CBS] / -2 * [#s_CS]) | StrokeWidth [#s_CloseCrossThick] | Stroke Color [#s_CloseCrossColor]
X=(-[#s_TopHeight] / 2)R
Y=( [#s_TopHeight] / 2)
LeftMouseUpAction=[!DeactivateConfig]

[CreditIcon2]
FontSize=[#s_CreditIconSize]
AntiAlias=1
Meter=String
Text=[\xF259]
FontWeight=400
Padding=0,0,0,0
DynamicVariables=1
SolidColor=0,0,0,1
MeterStyle=LeftPanel
FontColor=[#s_FontColor]
X=([#s_TopHeight] / 2) - ([#CURRENTSECTION#:H] / 2)
FontWeight=[#s_FontWeight]
FontFace=Segoe MDL2 Assets
ToolTipTitle=Generated by Settings
ToolTipText=https://github.com/sceleri/settings
LeftMouseUpAction=["https://github.com/sceleri/settings"]
Y=([#s_TopHeight] / 2) - ([#CURRENTSECTION#:H] / 2)

[TitleString]
Meter=String
$(if($Overrides.Title) {
"Text=$($Overrides.Title)"
} else {
"Text=Settings"
})
Text=$($Overrides.Title)
X=(([#s_TopHeight] / 2) - ([CreditIcon2:H] / 2) - 2)R
Y=(([#s_TopHeight] / 2) - ([#CURRENTSECTION#:H] / 2) + [#s_TitleNudge])
;X=((([#s_LeftPanelW] + [#s_RightPanelW]) / 2) - ([#s_TitlePadding] / 2))
;W=(([#s_LeftPanelW] + [#s_RightPanelW]) - ([#s_TitlePadding] * 2))
StringAlign=[#s_TitleAlign]
FontFace=[#s_TitleFont]
FontSize=[#s_TitleSize]
FontColor=[#s_TopFontColor]
AntiAlias=1
DynamicVariables=1


"@

