[Variables]
s_FontFace=Segoe UI
s_IconFontFace=Segoe UI

s_FontSize5 = 8
s_FontSize4 = 10
s_FontSize3 = 12
s_FontSize2 = 16
s_FontSize1 = 20

s_LeftPanelW = 200
s_RightPanelW = 600
s_PanelH = 700

s_SideBarItemPadding = 10
s_VariableItemPadding = 10
s_CategoryTopPadding = 40

s_SelectedFontWeight = 500
s_TitleFontWeight = 500

s_RightPanelBackgroundColor=255,255,255
s_LeftPanelBackgroundColor=200,200,200,200

s_BackgroundRounding=5

s_CurrentCategory=0