[Variables]
s_FontFace=Segoe UI
s_IconFontFace=Segoe MDL2 Assets
s_FontColor=0,0,0

s_ScrollSpeed = 10
s_Scroll = 0

s_FontSize5 = 8
s_FontSize4 = 10
s_FontSize3 = 12
s_FontSize2 = 16
s_FontSize1 = 20
s_InputTextFontSize=#s_FontSize3#

s_LeftPanelW = 200
s_RightPanelW = 600
s_PanelH = 700

s_ListIconLeftPadding=20
s_ListItemPadding=5
s_ListItemLeftPadding=10
s_ListItemTopPadding = 7
s_ListIconTopPadding = 10

s_VariablePadding = 20
s_VariableLeftPadding = 20

s_CategoryTitleTopPadding = 35
s_CategoryIconTopPadding = 40
s_CategoryIconLeftPadding = 20

s_SelectedFontWeight = 500
s_TitleFontWeight = 500

s_RightPanelBackgroundColor=255,255,255,255
s_LeftPanelBackgroundColor=200,200,200,200

s_ToggleActiveColor=0,0,255,255
s_ToggleInactiveColor=[#s_RightPanelBackgroundColor]
s_ToggleSize=20
s_TogglePadding=2.5

s_BackgroundRounding=5

s_CurrentCategory=0

