[FirstItemL]
H=0
W=0
SolidColor=0,0,0,0
Container=LeftPanel
Y=0
[FirstItemR]
H=0
W=0
SolidColor=0,0,0,0
Container=RightPanel
Y=0


[CategoryTitle]
FontFace=#s_FontFace#
AccurateText=1
AntiAlias=1
FontWeight=#s_TitleFontWeight#
FontSize=#s_FontSize1#
Padding=[#s_VariableItemPadding],[#s_CategoryTopPadding],[#s_VariableItemPadding],[#s_VariableItemPadding]
Container=RightPanel
Y=0R

[VarTitle]
FontFace=#s_FontFace#
AccurateText=1
AntiAlias=1
FontSize=#s_FontSize2#
FontWeight=#s_TitleFontWeight#
Padding=[#s_VariableItemPadding],[#s_VariableItemPadding],[#s_VariableItemPadding],[#s_VariableItemPadding]
Container=RightPanel
Y=0R

[VarDescription]
FontFace=#s_FontFace#
AccurateText=1
AntiAlias=1
FontSize=#s_FontSize4#
Padding=[#s_VariableItemPadding],0,[#s_VariableItemPadding],0
Container=RightPanel
Y=(-[#s_VariableItemPadding])R

[VarStringValue]
FontFace=#s_FontFace#
AccurateText=1
AntiAlias=1
FontSize=#s_FontSize3#
Padding=[#s_VariableItemPadding],[#s_VariableItemPadding],[#s_VariableItemPadding],[#s_VariableItemPadding]
Container=RightPanel
Y=0R

[VarColorValue]
Padding=[#s_VariableItemPadding],[#s_VariableItemPadding],[#s_VariableItemPadding],[#s_VariableItemPadding]
Container=RightPanel
Y=0R