[CategoryIcon{Index}]
Meter=String
Text={Icon}
MeterStyle=CategoryIcon | {Container}

[Title{Index}]
Meter=String
Text={Name}
MeterStyle=CategoryTitle | {Container}
W=([#s_RightPanelW] - [CategoryIcon{Index}:W])

[CategoryDescription{Index}]
Meter=String
Text={Description}
MeterStyle=VarDescription | ThickDescription | {Container}

[CategoryTitleSeparator{Index}]
Meter=Image
MeterStyle=CategoryTitleSeparator | {Container}

